// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmWqO_-kN-7bICfOb75-xYJKltnSD3tiE',
    appId: '1:32040171119:android:54ae5aac9930817e997f9a',
    messagingSenderId: '32040171119',
    projectId: 'photo-dairy-tutorial',
    storageBucket: 'photo-dairy-tutorial.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSlhXSyhh3-ywh34oCGQw4wVAOniN-Fb0',
    appId: '1:32040171119:ios:dca4cf1feb14c636997f9a',
    messagingSenderId: '32040171119',
    projectId: 'photo-dairy-tutorial',
    storageBucket: 'photo-dairy-tutorial.appspot.com',
    iosBundleId: 'com.example.photoDiaryFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBao550VP5vlFgULMnPQYizzkaCSLTr5dk',
    appId: '1:32040171119:web:596dbc96cba20fe6997f9a',
    messagingSenderId: '32040171119',
    projectId: 'photo-dairy-tutorial',
    authDomain: 'photo-dairy-tutorial.firebaseapp.com',
    storageBucket: 'photo-dairy-tutorial.appspot.com',
  );
}
